import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Precos from '../components/Precos'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Barbearia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className={styles.body}>
        <header className={styles.header}>
          <span className={styles.logo}>
            <Image src="/Logo_nova_imagem_png.png" alt="Nova Imagem Logo" width={300} height={40} />
          </span>
          <nav className={styles.navmenu}>
            <ul>
              <li><a href="/">Sobre</a></li>
              <li><a href="/">Serviços</a></li>
              <li><a href="/">Contato</a></li>
            </ul>
          </nav>
        </header>

        <div id={styles.main}>
          <article className={styles.article}>
            <Precos/>
          </article>
          <nav className={styles.nav}>
          <ul>
              <li><a href="/precos">Nossos Preços</a></li>
              <li><a href="/">Galeria</a></li>
              <li><a href="/">Outros Produtos</a></li>
            </ul>
          </nav>
          <aside className={styles.aside}>Barra Lateral</aside>
        </div>

        <footer className={styles.footer}>
          Rodapé
          <p>© 2022 Salão Nova Imagem. Todos os direitos reservados • Termos de Uso Política de Privacidade</p>
        </footer>

      </body>
    </div>
  )
}
