import styles from '../styles/Home.module.css'
import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Barbearia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className={styles.body}>
        <header className={styles.header}>
          <a href="/Logo_nova_imagem_png.png">Logo</a>
          <nav className={styles.navmenu}>
            <ul>
              <li><a href="/">Sobre</a></li>
              <li><a href="/">Produtos</a></li>
              <li><a href="/">Contato</a></li>
            </ul>
          </nav>
        </header>

        <div id={styles.main}>
          <article className={styles.article}>Conteúdo</article>
          <nav className={styles.nav}>Navegação</nav>
          <aside className={styles.aside}>Barra Lateral</aside>
        </div>

        <footer className={styles.footer}>
          Rodapé
          <p>© 2022 Salão Nova Imagem. Todos os direitos reservados • Termos de Uso Política de Privacidade</p>
        </footer>

      </body>
    </div>
  )
}
